- hosts: hp_host
  user: test
  become: true
  become_method: sudo
  gather_facts: yes
  tasks:
  - include_role:
      name: Jenkins_install

# - name: Get initial Admin password
#   command: 'cat /var/lib/jenkins/secrets/initialAdminPassword'
#   register: pass_variable

# - debug:
#     msg: "{{ pass_variable }}"

  - name: Pause until initial config is done
    pause:
      prompt: Please enter the username you have set in Jenkins
    register: jenkins_username
    #minutes: 5

  - debug:
      msg: "{{ jenkins_username }}"

  - pause: 
      prompt: Please enter the password you have set in Jenkins
      echo: no
    register: jenkins_password
    no_log: true

  - include_role:
      name: Jenkins_setup
